### PR TITLE
Remove kovarex-enrichment-process insertion for artillery-atomics

### LINKED ISSUE #15: Research prerequisite kovarex-enrichment-process breaks artillery-atomics
Unsure why specifically but currently playing in a modpack with Space Exploration and `artillery-atomics` is un researchable if the `kovarex-enrichment-process` is added as a prerequisite making progression impossible.

### PR DESCRIPTION
**Pull request by Inrixia**
Fixes https://github.com/More-Wrong/Factorio-True-Nukes/issues/15

If you want to discuss a better fix please let me know, happy to discuss.

### CODE REVIEW

**Comment by More-Wrong** [comment]
Hi, that would be the fix, but as far as I can tell, the issue doesn't lie with base SE nor the SE official modpack, so doing the changes under SE would break the mod for people playing with just SE.
I'll work with you on finding the offending mod in the issue you raised.

**Comment by Inrixia** [comment]
Re #15 the additional check should fix this without breaking SE

**Comment by More-Wrong** [comment]
Yup, that looks great, would you mind putting the same fix into line 69 as well?

**Comment by Inrixia** [comment]
Hey sorry for the delay. Looks like you'll sort it, thanks

**Pull request merged**
